---
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gradle" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
