---
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  indentation:
    spaces: 2
    indent-sequences: false

ignore:
# .github: Excluded as GitHub Actions YAML files are linted by Actionlint
- '.github'
