coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
