---
ktor:
  application:
    modules:
    - com.example.ApplicationKt.module
  deployment:
    port: 8080
    banner: "ASDF"
authentication:
  sessionCookieName: "example-cookie-id"
  sessionSigningKey: "6819b57a326945c1968f45236589"
  oAuth:
    callbackUrl: "http://localhost:8080/callback"
    clientId: ${AUTHENTICATION_OAUTH_CLIENTID}
    clientSecret: ${AUTHENTICATION_OAUTH_CLIENTSECRET}
database:
  url: "jdbc:postgresql://localhost:5432/todo"
  user: todo
  password: todo
  poolSize: 20
redis:
  host: localhost
  port: 6379
  password: valkey
